apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: staging-cluster-issuer
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: afsmithcodes@gmail.com
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
    - dns01:
        route53:
          hostedZoneID: XXXXXXXXXXXXXXXXXXXX
          region: us-east-1
      selector:
        dnsZones:
        - "smithashleyprojects.com"
    - http01:
        ingress:
          class: istio
