apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter
  namespace: staging
  annotations: 
        checkov.io/skip1: CKV_K8S_8
        checkov.io/skip2: CKV_K8S_9
  labels:
    app: counter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: counter
  template:
    metadata:
      labels:
        app: counter
    spec:
      automountServiceAccountToken: false
      securityContext:
        seccompProfile:
            type: RuntimeDefault
        runAsNonRoot: true
        runAsUser: 10014
      containers:
      - name: counter-pod
        image: smithashley/stateful-counter@sha256:ce88143a310e5e875b65a7766a1394c2728504b30565ca6bbf7439c437894166
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 10014
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "16Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
