#Specify ports to receive traffic
apiVersion: networking.istio.io/v1alpha3
kind: Gateway 
metadata:
  name: counter-gateway
  namespace: staging
spec:
  selector:
    istio: ingressgateway 
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE                          
      credentialName: tls-secret 
    hosts:
    - "*"