apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: counter-network-policy
  namespace: staging
spec:
  podSelector:
    matchLabels:
      app: counter
  namespaceSelector:
    matchLabels: {}
  policyTypes:
  - Ingress
  ingress:
  - from:
      - namespaceSelector:
          matchLabels: {}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: db-network-policy
  namespace: staging
spec:
  podSelector:
    matchLabels:
      app: postgres
  namespaceSelector:
    matchLabels: {}
  policyTypes:
  - Ingress
  ingress:
  - from:
      - namespaceSelector:
          matchLabels: {}