apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-claim
  namespace: staging
  labels:
    app: postgres
spec:
  storageClassName: ebs-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi