apiVersion: v1
kind: ServiceAccount
metadata:
  name: istio-sa
  namespace: staging
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cert-manager-read-role
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["tls-secret"]
  verbs: ["get"]
- apiGroups: ["cert-manager.io"]
  resources: ["certificates"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: istio-sa-binding
  namespace: istio-system
subjects:
- kind: ServiceAccount
  name: istio-sa
  namespace: staging
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-manager-read-role
