apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: counter-role
  namespace: staging
rules:
- apiGroups: [""]
  resources: ["pods", "services", "secrets", "configmap"]
  verbs: ["get", "read"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: counter-binding
  namespace: staging
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: counter-role