apiVersion: v1
kind: ServiceAccount
metadata:
  name: istio-sa
  namespace: staging
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tls-secret-role
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["tls-secret"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: istio-sa-binding
  namespace: istio-system
subjects:
- kind: ServiceAccount
  name: istio-sa
  namespace: staging
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tls-secret-role