apiVersion: v1
kind: Service
metadata:
  namespace: staging
  name: counter-app-service
  labels:
    app: counter
spec:
  type: ClusterIP
  ports:
    - name: tcp
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: counter
