apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: staging
spec:
  replicas: 1
  serviceName: postgres
  selector:
    matchLabels:
      app: postgres
      namespace: staging
  template:
    metadata:
      labels:
        app: postgres
      annotations:
        seccomp.security.alpha.kubernetes.io/pod: "runtime/default"
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 10015
      terminationGracePeriodSeconds: 5
      containers:
        - name: postgres
          image: postgres@sha256:021d7d217750a1b97b2232c1be9331eaa3f7d90a8a1bb2e9c25cd04a28e8306c
          securityContext:
            seccompProfile:
              type: RuntimeDefault
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 10015
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
          imagePullPolicy: Always
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
            - mountPath: /docker-entrypoint-initdb.d
              name: init
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 250m
              memory: 128Mi
            livenessProbe:
              httpGet:
                path: /healthz
                port: 5432
              initialDelaySeconds: 15
              periodSeconds: 20
            readinessProbe:
              httpGet:
                path: /ready
                port: 5432
              initialDelaySeconds: 5
              periodSeconds: 10
      volumes:
        - name: postgredb  
          persistentVolumeClaim:
            claimName: postgres-pv-claim
        - name: init
          secret:
            secretName: db-password
          configMap:
            name: postgres-config
            items:
            - key: init
              path: init.sql