apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: counter-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/smithashley/Kubernetes-Deployment-2.git
    targetRevision: main
    path: counter-app/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
