apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter-app
  namespace: staging
  labels:
    app: counter
spec:
  replicas: 2
  selector:
    matchLabels:
      app: counter
  template:
    metadata:
      # annotations:
      labels:
        app: counter
    spec:
      containers:
        - name: counter
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
          image: public.ecr.aws/aws-containers/stateful-counter:latest
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 64Mi
